import Head from "next/head";
import { useRouter } from 'next/router'
import React, { useEffect, useState } from 'react'

import dynamic from 'next/dynamic';



const Home = () => {
	let port: any, reader: any, log: any, writer: any
	let lineReader: any = undefined
	const loadSerialPorts = async() => {
		if ('serial' in navigator) {
			try {
				port = await navigator.serial.requestPort();
				await port.open({ baudRate: 115200, bufferSize: 1024, dataBits: 8, parity: "none", stopBits: 1 });
				lineReader = port.readable
					.pipeThrough(new TextDecoderStream())
					.pipeThrough(new TransformStream(new LineBreakTransformer()))
					.getReader();
				monitorPort()
			}
			catch (err) {
				console.error('There was an error opening the serial port:', err);
			}
		}
		else {
			console.error('The Web serial API not enabled in your browser.');
		}
	}

	class LineBreakTransformer {
		constructor() {
		  this.container = '';
		}
	  
		transform(chunk, controller) {
		  this.container += chunk;
		  const lines = this.container.split('\r\n');
		  this.container = lines.pop();
		  lines.forEach(line => controller.enqueue(line));
		}
	  
		flush(controller) {
		  controller.enqueue(this.container);
		}
	}
	  
	
	const monitorPort = async()=>{
		while (port.readable) {
			//const textDecoder = new TextDecoderStream();
			try {
				while (true) {
					const { value, done } = await lineReader.read();
					if (done) {
						// Allow the serial port to be closed later.
						reader.releaseLock();
						
						break;
					}
					if (value) {
						console.log(value);
					}
				}
			} catch (error) {
				// TODO: Handle non-fatal read error.
			}
		}
	}

	
	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
				<meta name="theme-color" content="#90cdf4" />
				<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.1/leaflet.css" />
        <link href="https://unpkg.com/leaflet-geosearch@latest/assets/css/leaflet.css" rel="stylesheet" />
			</Head>
			<div>
				<button onClick={loadSerialPorts}>Connect to Receiver</button>
			</div>
			<div>
			</div>
		</>
	);
};

export default Home;